### ISSUE TITLE
Error: Internal error in `vec_slice_impl()`: Unexpected `NULL`.

### ISSUE THREAD

**Issue by gutierrezphd** [AdrielC/autotradeR#1]
I have downloaded the .RProj for your in-development autotradeR package, and I am unable to scrape Autotrader successfully. The R function files load successfully, but I am getting the following error when attempting to run the first R chunk in the .Rmd:

 Error: Internal error in `vec_slice_impl()`: Unexpected `NULL`.

Full code is below: 

> library(tidyverse)
> library(rvest) # read_html functions and the like
> library(httr)
> library(pbapply) # For progress bars in queries
> library(parallel) # For parallel processing
> 
> Currently this is not built as a package yet, so just source all the files in the functions folder
> source("R/Functions/autoTrader_scrape.R")
> source("R/Functions/autoTrader_query.R")
> source("R/Functions/data_clean.R")
> source("R/Functions/info_extractors.R")
> source("R/Functions/scrape_utils.R")
> 
> ProvoJeepP <- autoTrader_scrape(make = "Jeep", model = "Wrangler", zip = 84604, pages = "all", sellerType = "p", locationName = "Provo", fork = 8)
Using 8 core(s) to scrape links
 Error: Internal error in `vec_slice_impl()`: Unexpected `NULL`.
Run `rlang::last_error()` to see where the error occurred. > 
> head(ProvoJeepP)
Error in head(ProvoJeepP) : object 'ProvoJeepP' not found
`

Traceback is as follows:

13.
stop(fallback) 
12.
signal_abort(cnd) 
11.
abort(message = message) 
10.
(function () 
abort(message = message))() 
9.
vec_rbind(!!!dots, .names_to = .id) 
8.
dplyr::bind_rows(list) at scrape_utils.R#182
7.
scraper_apply(., cl) at data_clean.R#5
6.
is.data.frame(x) 
5.
colnames(df) at data_clean.R#5
4.
"rowNum" %in% colnames(df) at data_clean.R#5
3.
clean_result_df(., locationName) 
2.
primaryQuery %>% query_URL_reader() %>% scraper_apply(cl) %>% 
    clean_result_df(locationName) at autoTrader_scrape.R#20
1.
autoTrader_scrape(make = "Jeep", model = "Wrangler", zip = 84604, 
    pages = "all", sellerType = "p", locationName = "Provo", 
    fork = 8)

**Comment by AdrielC** [comment]
Hi. Autotrader has updated their website since this version was first written. Currently updating the code now to reflect the latest Autotrader site version
